export const dataSource = [
  {
    id: 1,
    city: "Trindade",
    country: "Brasil",
    hotelName: "Hotel Trindade",
    hotelPhone: "556296416234",
    travelPlan: "Tem um bom ali...",
  },
  {
    id: 2,
    city: "Goiânia",
    country: "Brasil",
    hotelName: "Hotel Goiânia",
    hotelPhone: "556296416123",
    travelPlan: "Tem um bom ali...",
  },
  {
    id: 3,
    city: "Aparecida",
    country: "Brasil",
    hotelName: "Hotel Aparecida",
    hotelPhone: "556296416456",
    travelPlan: "Tem um bom ali...",
  },
  {
    id: 4,
    city: "Pirenópolis",
    country: "Brasil",
    hotelName: "Hotel Pirenópolis",
    hotelPhone: "556296416789",
    travelPlan: "Tem um bom ali...",
  },
  {
    id: 5,
    city: "Caldas Novas",
    country: "Brasil",
    hotelName: "Hotel Caldas Novas",
    hotelPhone: "556296416000",
    travelPlan: "Tem um bom ali...",
  },
];